PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# ami is the model, buzz is "my data"
# Make sure the ami5 collection _id = SCHEME has a prefixes entry
# that matches these!
PREFIX ami: <http://moschetti.org/ami#>
PREFIX ex: <http://moschetti.org/buzz#>


#
#  DOWNSTREAM
#

SELECT DISTINCT ?start ?end
WHERE {

#  Manual setting of components
#      BIND(<http://moschetti.org/buzz#myApp> AS ?components)
#

#  All components for a system; useful!
#  ex:system_001  ami:components  ?components .

#  Gets ALL components!  Less useful
#   ?components	a	ami:Component .
  
  {  
    ?components ami:connectsTo ?end .
    BIND(?components AS ?start)
  } UNION {
    ?start ami:connectsTo ?end . 
    ?components ami:connectsTo+ ?start .
  }

}
